apiVersion: v1
kind: Secret
metadata:
  name: kc-pk-secret
type: Opaque
stringData:
  KC_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\n<result of `curl https://your-SSO-instance/auth/realms/your-realm | jq '.public_key'` here>\n-----END PUBLIC KEY-----\n"
