apiVersion: v1
kind: Secret
metadata:
  name: kc-pk-secret
type: Opaque
stringData:
  KC_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAixI2BLlfJlcAThNhTDpVmswnIUMpQnBs2MX85Xys2MXnqUBMWMFfa2uCVEvZrW2N8wpPpCU4KI6YcVmf9bfsxPLs0heA5v7bFz+EkoefM8fLEINMopAHxvFuXGunvFIMsIxCMpMrI3AirDBh/dx0LUqqaKFRpYq65jYUBopVmhQ2UpJlJMEM2XihB3MEh5j/xW1dt/bFGVNuEy6nbdUfsjimDGiON+WbrzFP9H4Iupak/eT1AyUJ/jhxuzzX4LyIuLJr/xB3HsXDZy8LuvLF/ydvqY4NaHQhInozFCqLPXdpG+LEw1fczXv5nkWKg2OBr0ZRYHwIDAQAB\n-----END PUBLIC KEY-----\n"